### PR TITLE
Add Nextdns Disguised Third-Party Tracker List

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
A small list that is included with nextdns and it should be included here in my opinion

### CODE REVIEW

**Comment by GiddyGoatGaming** [comment]
There’s also a disclaimer in the blocklist saying “for this blocklist to work, the blocking logic must wildcard match”. That’s not all the disclaimer says but that’s the important part of it

**Comment by ignoramous** [comment]
serverless-dns already uncloaks `CNAME`s (NextDNS does too). What's the use of this list, would you know?

**Comment by GiddyGoatGaming** [comment]
Nextdns says this

“Automatically detect and block third-party trackers disguising themselves as first-party to circumvent recent browser's privacy protections like ITP”

**Comment by ignoramous** [comment]
This list is too small. Besides, almost all entries I checked from this list is present in CPBL, 1Hosts, StevenBlack or others. Given that all 3 of those are rethinkdns recommended blockists, a separate entry for just *cname blocking* isn't really required. What do you think?

**Comment by GiddyGoatGaming** [comment]
Not sure. If those lists contain most of these entries. I guess it isn’t much needed. There is a adguard cname tracker list with about 50k entries. Would that be more suitable do you think?

**Comment by ignoramous** [comment]
> There is a adguard cname tracker list with about 50k entries. Would that be more suitable do you think?

Can add it to the existing AdGuard list, as an additional entry, yeah.

**Comment by ignoramous** [comment]
Thanks! (:

**Comment by GiddyGoatGaming** [comment]
> Thanks! (:

No thank you!

**Pull request merged**
