### PR TITLE
Jarelllama's Scam Blocklist

### PR DESCRIPTION
**Pull request by jarelllama**
Blocklist for newly created scam and phishing domains automatically retrieved daily using Google Search API, automated NRD detection, and other public sources.

The blocklist aims to be an alternative to blocking all newly registered domains (NRDs) seeing how many, but not all, NRDs are malicious. A variety of sources are integrated to detect new malicious domains within a short time span of their registration date.

https://github.com/jarelllama/Scam-Blocklist

Currently integrated into Hagezi's TIF blocklist and the oisd blocklist.

### CODE REVIEW

**Comment by ignoramous** [comment]
Think we have got a bit of cleaning to do. I'll merge this when I get around to doing it (which should be *soon*). https://github.com/celzero/rethink-app/issues/1359

**Comment by jarelllama** [comment]
If you'd appreciate some help going through the filter lists, I could manually go through some of them and open pull requests with the dead/inactive ones removed.

**Comment by ignoramous** [comment]
> Currently integrated into Hagezi's TIF blocklist and the oisd blocklist.

If Jarelllama's list is already merged into HaGeZi's TIF and OISD, do we need to add it (as both those are already covered)?

**Comment by ignoramous** [comment]
I see your lists has other subset categories (emerging-threats, nsfw, malware, nrd, parked-domains, homograph). Does HaGeZi cover 'em all?

**Comment by jarelllama** [comment]
Hagezi's TIF list contains everything but NSFW. The NSFW list is contained in OISD's NSFW list.

**Comment by jarelllama** [comment]
My mistake, Hagezi's TIF list does not contain the parked domains list.

**Comment by ignoramous** [comment]
Hi @jarelllama If you want us to include any other list missing from existing aggregated lists, let us know! Happy to include them.

**Pull request closed without merging**
