### PR TITLE
Added Yet another small uBlock filter list

### PR DESCRIPTION
**Pull request by mtxadmin**

### CODE REVIEW

**Comment by ignoramous** [comment]
[yasufl](https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt) has 800K+ entries. Hopefully including it doesn't break github action to build the [compact radix-trie](https://github.com/celzero/gotrie) which is already pretty close to the 8GB RAM limit.

**Comment by ignoramous** [comment]
Thanks for the submission. These blocklists would be part of the next build (we run that every monday, but aren't doing that until end of November because of a _bug_ in the RethinkDNS clients that download these, which we hope to update by then).

**Comment by ignoramous** [comment]
@mtxadmin the blocklist is live: https://rethinkdns.com/configure#1:EAAIAA== :)

**Comment by ignoramous** [comment]
Sample search: https://rethinkdns.com/search?q=segment.io

**Comment by mtxadmin** [comment]
Big thanks for this grate tool! Very useful.

**Pull request merged**
