### PR TITLE
Switch some lists to Ultimate Host Blocklist pt 1

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Also switched a list from hosts to domains

### CODE REVIEW

**Comment by ignoramous** [comment]
These Ultimate-Hosts-Blocklist look pretty good to me. The only concern is they seem to maintain their own Whitelist... https://github.com/Ultimate-Hosts-Blacklist/whitelist Would that surprise folks not expecting a 3p whitelist to override these other lists?

**Comment by GiddyGoatGaming** [comment]
> These Ultimate-Hosts-Blocklist look pretty good to me. The only concern is they seem to maintain their own Whitelist... https://github.com/Ultimate-Hosts-Blacklist/whitelist Would that surprise folks not expecting a 3p whitelist to override these other lists?

I doubt it would surprise folks but you never know

**Comment by ignoramous** [comment]
As good as the Ulimate Host mirror may be, I am thinking we should stick to the original source? I briefly spoke with folks running other content-blocking DNS services, and they said that replacing original source with mirror tends to lead to confusion for both the list-maintainer and the list-user. Thoughts?

**Comment by GiddyGoatGaming** [comment]
> As good as the Ulimate Host mirror may be, I am thinking we should stick to the original source? I briefly spoke with folks running other content-blocking DNS services, and they said that replacing original source with mirror tends to lead to confusion for both the list-maintainer and the list-user. Thoughts?

Yeah sure, that makes sense. Il close this now👍

**Pull request closed without merging**
