### PR TITLE
Add Block List Project: Ads

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Just a good quality blocklist

### CODE REVIEW

**Comment by ignoramous** [comment]
Pls add this blocklist the end. How many entries in there, btw?

Is this list a collection of other lists? If so, rethinkdns has plenty such lists already.

**Comment by GiddyGoatGaming** [comment]
There appears to be 154563 domains at the time I’am writing this. I can’t find any information on if there’s any merged lists so I’m assuming it’s curated by the maintainer himself. If you want more information the link to the GitHub is https://github.com/blocklistproject/Lists

**Comment by ignoramous** [comment]
Thanks. Btw, this list needs to go at the end of the json.

**Comment by GiddyGoatGaming** [comment]
Ok, I think I put it where you asked. Just let me know if there’s anything else you need me to do👍

**Comment by ignoramous** [comment]
Hi, this commit needed some more changes (for ex, `format` is `hosts` not `domains`), which I made them myself. But I didn't have the requisite permissions to update this PR, and so, I created a separate commit and merged it in: https://github.com/serverless-dns/blocklists/commit/443a4fedded9cb8f4a91a13e11910304e402cf5b

**Pull request closed without merging**
