### PR TITLE
Remove Porn (Sinfonietta) and replace with Energized Porn Lite

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Hasn't been updated since August 2018. Over 4 years ago

### CODE REVIEW

**Comment by ignoramous** [comment]
Hi: The commit removes Mahadi's list, instead.

Also, mark em "dead" or replace them with another equivalent list (like say, Hagezi or RPi or ShadowWhisperer or Energized etc)

**Comment by GiddyGoatGaming** [comment]
Ok. Il change that in a bit. Thanks for letting me know

**Comment by GiddyGoatGaming** [comment]
So I changed it and replaced it with porn lite energized. The commit makes it look like it messed up everything but as soon as I click the file, it looks fine to me. Not sure, maybe im missing something. I don’t know

**Comment by GiddyGoatGaming** [comment]
Just realized that the porn lite list includes sinfonietta as one of the blocklists so it would essentially be a more effective version of that list (hopefully)

**Comment by GiddyGoatGaming** [comment]
Oisd nsfw also includes this list. I feel like in general, you could just get rid of sinfonietta’s list altogether and it wouldn’t be bad. Up to you

**Review by ignoramous — APPROVED** [review]

**Comment by ignoramous** [comment]
Thanks!

**Pull request merged**
