### PR TITLE
Add Game Console Adblock List

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
A very tiny list that is included in adguards private dns service but not included here. Might be useful to a few people

### CODE REVIEW

**Comment by GiddyGoatGaming** [comment]
Also, adguard labels this blocklist as having 10 rules.

**Comment by ignoramous** [comment]
Yeah, too few rules and I don't think this list any effective?

**Comment by GiddyGoatGaming** [comment]
I feel like this list could appeal to a select few. Other lists like Oisd do not include this list and I have not found any other major list to include these rules in them.

**Comment by ignoramous** [comment]
Is there a host file / domains file? This one is `abp`.

**Comment by GiddyGoatGaming** [comment]
I cannot find any other version that is not abp format. If you cannot add this list due to this limitation. Fill free to close this pull request

**Pull request closed without merging**
