### PR TITLE
Mark Adult (Mahadi Xion) dead until a replacement can be found

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Hasn’t been updated since august 2018 according to the blocklist and according to the repo, it has only been updated less then 10 times since then and was only for a single domain at a time. I think a replacement should be found but I’m unsure of what to replace it with, at this point in time

### CODE REVIEW

**Comment by ignoramous** [comment]
Lets leave it up since it is a list that's marked "level 0" and likely in use by folks. Zero'ing it out spells more surprise... but let this PR be open so we know to look for a replacement. @Spirillen's lists could be used: https://github.com/mypdns/adblocker-rules.

**Comment by ignoramous** [comment]
All Spirillen's lists are 404, unfortunately: https://github.com/serverless-dns/blocklists/commit/465145489080d77453ad9d5fc6c8853bdfeb6950

**Comment by GiddyGoatGaming** [comment]
> All Spirillen's lists are 404, unfortunately: [4651454](https://github.com/serverless-dns/blocklists/commit/465145489080d77453ad9d5fc6c8853bdfeb6950)

Yeah, I noticed that for the past week but haven’t had any idea why. Hopefully it will be back up and running soon

**Comment by ignoramous** [comment]
Thanks for bringing both these lists to my notice:

I've now replaced mahadi xion adult lists with cbuijs compiled adult list: https://github.com/serverless-dns/blocklists/commit/00887f5bb407021353326605eae564a4a93b5ba5

**Comment by ignoramous** [comment]
Yeah, I found to be the case.

We did use the various *mypdns* lists (#107), but they went offline and I couldn't find a way to contact you...

**Comment by SpencerIsGiddy** [comment]
> Hey @ignoramous they have been relaunched here https://0xacab.org/my-privacy-dns/matrix as my friends got a powerbill of €7500, they determined to have the server taken down 😭
> 
> Next is I will no longer be active on GH from 24 of may do to the 2FA total tracking requirements.

€7500?!?! Oh Lordy🤯. Glad to see you have relaunched the service!

**Comment by spirillen** [comment]
Just wait a week or two ( if things goes as planned) Then there might even appears surprises... 

The commit/test/report tool is alive at https://0xacab.org/my-privacy-dns/matrix/-/blob/master/tools/client_web.md

**Comment by cbuijs** [comment]
> Just a little note about cbuijs adults lists, they are NOT curated, _and at least used to_, be full of FP domains

Hey @spirillen, could you provide some examples?

The Family-Safe list is not only adult themed, but utilizes multiple types of sources to protect the "Family" to content not suited. For example, whole hosters/hosting-sites are blocked because of the sheer amount of unwanted content  they host in general (like blogspot etc), and associated huge numbers of (sub) domains to keep the list manageable.

Let me know, and I can see how to improve/optimize if possible.

**Comment by spirillen** [comment]
Would like to, but I can't access you lists for now, ( I do not have the bandwidth), and as mentioned.. in the past, so I do not know if this is still the case, but as I recalls it there was some britneyspeers links in the top of the lists which have nothing to do on a NSFW/Family filter, as they where rather SFW and kindsfriendly form that point of view.

I also remembers I tried to put up a repo to crawl your lists with @pyfuncble where the results was about ~40% dead records.

To all above, please give some room for mistakes as this is 3 or 4 years ago

**Comment by cbuijs** [comment]
No worries. In the repo there is also a "[top-n](https://raw.githubusercontent.com/cbuijs/accomplist/master/family-safe/plain.black.top-n.domain.list)" list, which only contains "active" domains that are actually queried, and is much shorter. It is based on several Top-1M lists available and is updated every 24 hours as well.

I have created another repo called "[adult-themed](https://github.com/cbuijs/accomplist/tree/master/adult-themed)", similar setup but **only** contain adult/porn/nsfw related content. It also contains a "[top-n](https://raw.githubusercontent.com/cbuijs/accomplist/master/adult-themed/plain.black.top-n.domain.list)" list. This should keep the number of false-positive on non-adult domains way low.

Hope this clears it up, makes sense and helps ;-).

**Comment by spirillen** [comment]
@cbuijs So you believe you have a rather curated NSFW lists that could match our definition (https://0xacab.org/my-privacy-dns/matrix/-/tree/master/source/porn_filters#classifications-definitions) of NSFW?

Which of your lists do you believe should be the best match for the Adult blocking project?

In that case would you like to cooperate by allowing My Privacy DNS to use your list as external source and IF also believes your lists have a very low FP the same way as we do with @ShadowWhisperer lists?

PS: I have open a similar issue here:  As I get 1. locked out in a few days, 2. This is not the place to talk about this

**Comment by spirillen** [comment]
>  I just use sources I deem to be fine

Hmm let me give you a hint then, after a retest...

try running this code against your lists and count the diff.

```bash
sed -iE '/^([a-z0-9_-]{1,})\.blogspot\.[a-z]{2,3}([.][a-z]{2})?$/d;/^([a-z0-9_-]{1,})\.tumblr\.com$/d;/^([a-z0-9_-]{1,})\.weebly\.com$/d' path/to/your/file
```
This would help remove the worst ~6.500.00 dead and useless records, as blogspot is only served on `blogspot.com` and all other `blogspot.TLD` are redirected there

tumblr and weebly do not permit adult contents and such subdomains are taken down on reporting or they found them themself.

Next I do find a lot of dead domains + False positives: Currently counting ~27.000 records https://0xacab.org/my-privacy-dns/matrix/-/issues/?search=https%3A%2F%2Fgithub.com%2Fcbuijs%2Faccomplist%2Fblob%2Fmaster%2Fadult-themed%2Fplain.black.domain.list&sort=created_date&state=all&or%5Blabel_name%5D%5B%5D=On_Hold%3A%3AUnConfirmed&or%5Blabel_name%5D%5B%5D=Wontfix&in=DESCRIPTION&first_page_size=20

> Not sure why you are getting locked out,

I'm not going to implant any  2FA(ggots) spyware/tracking on any of my devices.

> Not sure if I would be a great contributor

You can simply install the Firefox add-on for reporting: https://0xacab.org/my-privacy-dns/matrix/-/blob/master/tools/client_addon.md
or use our webbased tool box: https://0xacab.org/my-privacy-dns/matrix/-/blob/master/tools/client_web.md

The addon comes with a bulk commit tool vs the webbased, where you only can add one domain at the time. But you can do that anonymously vs the add-on which requires a personal [API-key](https://0xacab.org/-/profile/personal_access_tokens?name=mypdnsrep-addon&scopes=read_user,api)

Another add-on allows you to use our blacklist per category with a local whitelist

Give it a look

**Comment by cbuijs** [comment]
Try to use the Top-N version as I suggested earlier, it only contains active domains based on top-n lists/input from various sources:

https://raw.githubusercontent.com/cbuijs/accomplist/master/adult-themed/plain.black.top-n.domain.list

**Comment by cbuijs** [comment]
Try to use the Top-N version as I suggested earlier, it only contains active domains based on top-n lists/input from various sources:

https://raw.githubusercontent.com/cbuijs/accomplist/master/adult-themed/plain.black.top-n.domain.list

**Comment by spirillen** [comment]
> Try to use the Top-N version as I suggested earlier, it only contains active domains based on top-n lists/input from various sources:
> 
> https://raw.githubusercontent.com/cbuijs/accomplist/master/adult-themed/plain.black.top-n.domain.list

Would you mind post it to https://0xacab.org/my-privacy-dns/support/-/issues/143 so cat/limonade can see it, it is them who put of the job on there backends

**Comment by cbuijs** [comment]
@spirillen Done!

**Pull request closed without merging**
