### PR TITLE
Config: Update unified blocklist source

### PR DESCRIPTION
**Pull request by SpencerIsGiddy**
The source for the unified blocklist has recently been updated. This pr request changes the source link

### CODE REVIEW

**Comment by ignoramous** [comment]
I prefer the GitHub link if it is continued to be maintained...

**Comment by SpencerIsGiddy** [comment]
As of currently, the link to the GitHub link is giving a 404 error and I can’t seem to find a new place that the blocklist is in (that is for the GitHub repo)

**Comment by ignoramous** [comment]
Should we then replace this list?

**Comment by SpencerIsGiddy** [comment]
Well the list is still working at the new url so I would keep it. I like the unified blocklist so I would prefer to keep the list on rethinkdns

**Comment by ignoramous** [comment]
Done. Thanks.

**Pull request merged**
