### PR TITLE
Change Cats Team blocklist to domains from hosts

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Reduces file size from 1.67mb file size to 1.15mb

### CODE REVIEW

**Review by ignoramous — COMMENTED** [review]
Note: Doing so only affects the download size (also negligible because most blocklist transfers happen `gzip`ped over `http`, which usually compresses blocklists by 50%). When building the trie, only domain names are kept. IPs and other metadata like abp or regex expressions are discarded.

**Comment by GiddyGoatGaming** [comment]
oh i see

**Comment by ignoramous** [comment]
Although, preferable to use `domains` format since there's little pre-processing required. Lesser chance of bugs getting in the way ;)

**Comment by GiddyGoatGaming** [comment]
Ok, il keep that in mind👍

**Pull request merged**
