### PR TITLE
Add a URL Shortener list in blocklistConfig.json

### PR DESCRIPTION
**Pull request by PeterDaveHello**
As a user requested in https://github.com/PeterDaveHello/url-shorteners/issues/2

### CODE REVIEW

**Review by ignoramous — APPROVED** [review]

**Comment by ignoramous** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@ignoramous as I haven't seen it on the website, may I ask how long we usually take to get this change deployed and being effective? Thanks.

**Comment by ignoramous** [comment]
> @ignoramous as I haven't seen it on the website, may I ask how long we usually take to get this change deployed and being effective? Thanks.

I am fixing the Rethink blocklists automation (see the failed github-action runs and the many check-ins from the past few days). Once that's up, these should build the blocklists into the trie data-structure Rethink uses, about twice a week, without requiring human input.

I am also trying to get down the final trie size down by 10%, as with the recent additions to blocklists, it has grown to around an unworkable 120MB. Unworkable because we have only got 128MB RAM on Cloudflare Workers. I don't think we can afford to load a blocklist (trie) bigger than 90MB to 100MB.

The first and *key* optimization is complete (code to be pushed soon), and the second one is a bit tricky (and not as *key* as the first but required nonetheless) should be done by the end of this week. Post which, I expect to start publishing the trie to all clients (the Rethink DNS + Firewall app) and servers (on Cloudflare and Fly).

A bit of a mess, but the technical debt of 2 years has come due, imo.

**Comment by ignoramous** [comment]
@PeterDaveHello Live since today: https://sky.rethinkdns.com/1:EAAEAA== / 1-caaaiaa.max.rethinkdns.com (:

**Pull request merged**
