### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
I have found some lists to be more aggressive than what is stated with the number and some lists to be less aggressive. Unified blocklist for example has been very pleasant to use but small ublock filter has been a nightmare. Light switch tracking extended is a very aggressive list stated by the dev so I think it deserves a 2 rather then a 1.

### CODE REVIEW

**Review by ignoramous — APPROVED** [review]
Why mark Anti Pop Ads *dead*? Is it chronically out of maintenance?

Other than that, these look good. Will merge in before the next blocklist build. Thanks.

**Comment by GiddyGoatGaming** [comment]
> Why mark Anti Pop Ads _dead_? Is it chronically out of maintenance?
> 
> Other than that, these look good. Will merge in before the next blocklist build. Thanks.

So anti pop ads 2 is the one maintained by the same person as Energized

**Comment by ignoramous** [comment]
> So anti pop ads 2 is the one maintained by the same person as Energized. And it has been inactive since Energized went down

Is the current list problematic, though? Might still be useful with its existing blocks?

**Comment by GiddyGoatGaming** [comment]
> > So anti pop ads 2 is the one maintained by the same person as Energized. And it has been inactive since Energized went down
> 
> Is the current list problematic, though? Might still be useful with its existing blocks?

Well it is back to being updated so no need for it being marked dead

**Comment by ignoramous** [comment]
Thanks! (:

**Pull request merged**
